package com.cloud.assignment.assignment.webSource;

import com.cloud.assignment.assignment.Note.NoteRepository;
import org.apache.commons.codec.binary.Base64;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RestController;
import sun.misc.BASE64Decoder;

import java.io.IOException;

@RestController

public class Authorization  {

    @Autowired // get the bean called noteRepository
         // Which is auto-generated by Spring, used to handle the data
    private NoteRepository noteRepository;

    @Autowired
    private UserRepository userRepository;

    public User authorizeUser(@RequestHeader String Authorization){
        int index3 = Authorization.indexOf(" ");
        String code = Authorization.substring(index3+1);
        Base64 base64 = new Base64();
        BASE64Decoder decoder = new BASE64Decoder();
        String decode = null;

        try {
            decode = new String(decoder.decodeBuffer(code),"UTF-8");
        } catch (IOException e) {
            e.printStackTrace();
        }
        int index = decode.indexOf(":");

        String password = decode.substring(index+1);
        String email = decode.substring(0,index);

        User user = userRepository.findByEmail(email);
        if(user == null){
            return null;
        }else{
            if(BCrypt.checkpw(password,user.getPassword())){
                return user;
            }
        }
        return null;
    }
}
